<a href="https://colab.research.google.com/github/arash7m/UdemyPyTorch/blob/main/00_PyTorch_Fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.0.1+cu118


# Tensors

Tensors are the fundamental building block of machine learning.
Their job is represent data in a numerical way.
representing an image as a tensor with [3, 224, 224] which would mean [colour_channels, height, width].
It has 3 colour channels (RGB), and 224 by 224 pixels.
The tensors have three dimensions for Color, Height and Width.

In [3]:
# Scalar
# Scalar is a single number and in tensor-speak it's a zero dimension tensor.
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tesors)
scalar.item()

7

In [6]:
# Vector
# Vectors is a single dimension tensor but can contain many numbers. For example [3, 2] to describe [bedrooms, bathrooms] in your house.
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Check the dimensions of vector
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Check number of dimensions
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [28]:
# Create a random tensor of size (4, 5)
random_tensor = torch.rand(4, 5)
random_tensor

tensor([[0.0128, 0.8733, 0.9190, 0.9233, 0.5012],
        [0.3033, 0.8458, 0.8380, 0.7789, 0.5363],
        [0.8733, 0.4717, 0.1269, 0.8756, 0.5861],
        [0.0515, 0.2444, 0.5725, 0.8316, 0.6484]])

In [25]:
# Create a random tensor, with similiar shape to a tensor image
random_image_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [29]:
random_image_tensor

tensor([[[4.8695e-01, 1.1780e-01, 9.4862e-01,  ..., 2.7099e-01,
          1.9125e-01, 1.6237e-01],
         [2.5165e-01, 5.9744e-02, 2.5787e-01,  ..., 2.2346e-01,
          3.6083e-01, 7.8624e-01],
         [6.2098e-01, 5.0951e-01, 3.8660e-01,  ..., 8.3098e-01,
          3.3620e-01, 2.6112e-02],
         ...,
         [2.6482e-01, 5.4745e-01, 9.5037e-01,  ..., 4.0550e-01,
          6.9568e-01, 1.8860e-01],
         [2.2082e-01, 6.0226e-01, 2.7141e-03,  ..., 6.5519e-01,
          3.7170e-01, 8.1095e-01],
         [9.8852e-01, 8.0134e-01, 4.1875e-03,  ..., 9.4714e-01,
          8.3316e-01, 8.3748e-01]],

        [[7.7662e-01, 3.9083e-01, 9.1705e-01,  ..., 5.8049e-01,
          7.1074e-01, 1.9175e-01],
         [3.3785e-01, 9.2949e-01, 1.7348e-01,  ..., 4.8222e-01,
          7.7291e-01, 8.6750e-01],
         [6.3311e-01, 6.2372e-01, 5.7408e-01,  ..., 2.4507e-02,
          1.8182e-01, 7.6005e-01],
         ...,
         [1.5983e-01, 3.9360e-01, 6.2321e-01,  ..., 3.0764e-01,
          8.225

In [34]:
# Create a tensor of 1s and 0s
zeros = torch.zeros(size=(4, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [35]:
zeros*random_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [36]:
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [38]:
ones*random_tensor

tensor([[0.0128, 0.8733, 0.9190, 0.9233, 0.5012],
        [0.3033, 0.8458, 0.8380, 0.7789, 0.5363],
        [0.8733, 0.4717, 0.1269, 0.8756, 0.5861],
        [0.0515, 0.2444, 0.5725, 0.8316, 0.6484]])

In [39]:
ones.dtype

torch.float32

# Creating Range for Tensors and Tensor-likes

In [43]:
# Use Tensor.range()
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
torch.arange(1, 6, 2)

tensor([1, 3, 5])

In [47]:
torch.arange(1, 10.25, 0.75)

tensor([ 1.0000,  1.7500,  2.5000,  3.2500,  4.0000,  4.7500,  5.5000,  6.2500,
         7.0000,  7.7500,  8.5000,  9.2500, 10.0000])

# ** Tensor data types

Note: Most erros from tesnorflow stem from data types

1. Tensors aren't the right datatypes
2. Tensors aren't the right shape
3. Tensors aren't on the right device

In [2]:
# Float 32 tensor
random_tensor = torch.tensor ([3.0, 6.0, 9.0] ,
                              dtype=None,
                              device=None,
                              requires_grad=False)
random_tensor


tensor([3., 6., 9.])